apiVersion: v1
kind: Service
metadata:
  name: muse-glimmer-30b-service
  labels:
    app: muse-glimmer-30b
spec:
  type: ClusterIP
  selector:
    app: muse-glimmer-30b
  ports:
    - name: http
      port: 8000
      targetPort: 8000
