apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-3-3-70b-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-k8s-general
  resources:
    requests:
      storage: 100Gi
