apiVersion: v1
kind: Service
metadata:
  name: kisz-auth-wrapper-service
  labels:
    app: kisz-auth-wrapper
spec:
  type: ClusterIP
  selector:
    app: kisz-auth-wrapper
  ports:
    - name: http
      port: 80
      targetPort: http
