apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-proxy
spec:
  template:
    spec:
      nodeSelector:
        node-type: cpu
      containers:
        - name: litellm
          env:
            - name: LITELLM_ASSET_PREFIX
              value: /litellm-asset-prefix
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
