apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-proxy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    spec:
      nodeSelector:
        node-type: cpu
      containers:
        - name: litellm
          readinessProbe:
            httpGet:
              path: /litellm/.well-known/litellm-ui-config
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          env:
            - name: LITELLM_ASSET_PREFIX
              value: /litellm-asset-prefix
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
