apiVersion: v1
kind: Service
metadata:
  name: lora-manager
  labels:
    app: lora-manager
spec:
  type: ClusterIP
  selector:
    app: lora-manager
  ports:
    - name: http
      port: 8000
      targetPort: http
