apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litellm-staging

resources:
  - ../../base

patches:
  - path: patches/litellm-staging-config.yaml
  - path: patches/litellm-staging-service.yaml

replicas:
  - name: litellm-proxy
    count: 1
