apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litellm-staging

resources:
  - ../../base
  - ../../base/kisz-auth-wrapper

patches:
  - path: patches/litellm-staging-config.yaml
  - path: patches/litellm-staging-service.yaml
  - path: patches/kisz-auth-wrapper-staging-service.yaml
  - path: patches/kisz-auth-wrapper-staging-deployment.yaml

replicas:
  - name: litellm-proxy
    count: 1
