apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litellm

resources:
  - ../../base
  - ../../models
  - ingress.yaml
  - sealed-secrets/litellm-secret.yaml

patches:
  - path: patches/litellm-prod.yaml
  - path: patches/nginx-prod-service.yaml
  - path: patches/litellm-prod-authentik-sso.yaml

replicas:
  - name: litellm-proxy
    count: 2

images:
  - name: ghcr.io/aihpi/tool-litellm
    digest: sha256:117657d98541e14374a1c14e383bb030f3f81ff4592f79954fc0ea7043a89532
