apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen-model-storage
  namespace: litellm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 50Gi
