apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: granite-4-h-tiny-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 50Gi
