apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gemma-4-31b-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-k8s-general
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gemma-4-31b-adapters
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-k8s-general
  resources:
    requests:
      storage: 50Gi
