apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpt-oss-120b-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-k8s-general
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpt-oss-120b-adapters
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-k8s-general
  resources:
    requests:
      storage: 50Gi
