apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
spec:
  type: LoadBalancer
  selector:
    app: nginx-proxy
  ports:
    - name: http
      port: 4100       # External port exposed by the LoadBalancer
      targetPort: 4100 # Matches the nginx containerPort
      protocol: TCP
