apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
spec:
  type: LoadBalancer
  selector:
    app: nginx-proxy
  ports:
    - name: http
      port: 4000       # Match the original external port
      targetPort: 4000 # Match the Nginx containerPort
      protocol: TCP
