apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-omni-cache
  labels:
    app: qwen3-omni
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-k8s-general
  resources:
    requests:
      storage: 200Gi
