apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
  namespace: litellm
type: Opaque
stringData:
  LITELLM_MASTER_KEY: "CHANGE-ME-sk-..."
  DATABASE_URL: "postgresql://litellm:CHANGE-ME@postgres-service:5432/litellm"
  POSTGRES_PASSWORD: "CHANGE-ME"
  UI_USERNAME: "admin"
  UI_PASSWORD: "CHANGE-ME"
  HF_TOKEN: "hf_...REPLACE_ME"
  LDAP_BIND_DN: "CN=bind-user,OU=Users,DC=example,DC=org"
  LDAP_BIND_PASSWORD: "CHANGE-ME"
